#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 450

#define GAME_TITLE "WORLD SIMULATOR"

#define CAMERA_INTERVAL 100.0f

#define FPS 60

#define HUMUN_SIZE 2.5f
#define HUMUN_SIZE_R HUMUN_SIZE / 2

#define MAP_BLOCK_COUNT 10
#define MAP_SIZE HUMUN_SIZE *MAP_BLOCK_COUNT